services:
  app:
    build:
      context: .
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car-rental
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - car-rental-data:/var/lib/postgresql/data

volumes:
  car-rental-data:
